### ISSUE TITLE
[Linter] Error running Terraform See Console for more info.

### ISSUE THREAD

**Issue by marcinpiotrak** [mschuchard/linter-terraform-syntax#14]
Morning,
when added Terraform repo to my Atom I've been facing following error: 
[Linter] Error running Terraform See Console for more info.
and then:
[Linter] Error running Terraform ReferenceError: toReturn is not defined
    at /Users/mpiotrak/.atom/packages/linter-terraform-syntax/lib/main.js:210:11
    at <anonymous>

Atom version 1.35.1
MacOS version 10.14.4

Any help would be very appreciated!

Regards,
Marcin

**Comment by mschuchard** [comment]
You have to View --> Developer --> Toggle Developer Tools to see the console with your specific error.

**Comment by marcinpiotrak** [comment]
Morning @mschuchard 

much appreciated your prompt response!

This was in fact error from the console:
[Linter] Error running Terraform ReferenceError: toReturn is not defined
at /Users/mpiotrak/.atom/packages/linter-terraform-syntax/lib/main.js:210:11
at

once entered for more details it takes me to following index.html file

![image](https://user-images.githubusercontent.com/39948767/55057247-f3495100-5068-11e9-881f-f9d7161a749b.png)

**Comment by mschuchard** [comment]
So I added some code to fix #12, but it has caused a snag in this issue as a side effect. I have been aware of this because it also impacts some of my other packages (e.g. packer, vagrant, two ansible I think).

Basically you have an error but you cannot view the message because I am catching it and then checking if it is one specific error so stderr is getting gulped. Next steps for debugging would be going into the source code for the package in your local install and deleting these lines https://github.com/mschuchard/linter-terraform-syntax/blob/v1.2.6/lib/main.js#L197-L210.

After that, your specific error should display properly.

**Comment by marcinpiotrak** [comment]
Evening @mschuchard, it did display error message:
![image](https://user-images.githubusercontent.com/39948767/55108931-ee21eb80-50d4-11e9-91c5-ab19e19f5de8.png)
gonna give it some googling later on, unless you know some quick fix on this.
Thanks for your help!

**Comment by mschuchard** [comment]
That error usually shows up when the user running Atom does not have permission to execute your Terraform binary executable. That is a common issue on Windows, but it appears you are running Linux, so I would recommend a quick check on the permissions of your Terraform executable in the path of the user running Atom.

**Comment by marcinpiotrak** [comment]
Hi @mschuchard,

amazing support from your end. I have tackled around with permissions and executable path and it works like a charm now. Once again thank you for help!
