### ISSUE TITLE
Linting non terraform files when it shouldn't, Pulsar

### ISSUE THREAD

**Issue by peteristhegreat** [mschuchard/linter-terraform-syntax#23]
Right now if I open an `untitled` document, it immediately gets selected and linted by 
linter-terraform-syntax ... if I disable this package, then it doesn't.

I know I can override the grammar with `grammar-selector` `ctrl-shift-L`, but is there a setting to scope it down to just the terraform file types?

Maybe this is my issue with not having more linters installed and Pulsar doesn't know how to manage linters right yet.  Any recommendations?

linter-terraform-syntax v1.6.2
pulsar 1.63.2022120804 MacOS

**Comment by mschuchard** [comment]
Although officially I am still supporting Atom-dev 1.63 at the latest until Pulsar stabilizes, I can still confidently state this issue is unrelated to this package. You would need to investigate if this is a `language-terraform` or `language-hcl` issue (or possibly even an `atom-linter` or `pulsar` issue) and proceed from there.
